export const issuedTcType = {
	GET_ISSUEDTC_SUCCESS: "GET_ISSUEDTC_SUCCESS",
	GET_ISSUEDTC_FAILURE: "GET_ISSUEDTC_FAILURE",
	GET_ISSUEDTC_LOADING: "GET_ISSUEDTC_LOADING",

	GET_ISSUEDTC_BY_ID_SUCCESS: "GET_ISSUEDTC_BY_ID_SUCCESS",
	GET_ISSUEDTC_BY_ID_FAILURE: "GET_ISSUEDTC_BY_ID_FAILURE",
	GET_ISSUEDTC_BY_ID_LOADING: "GET_ISSUEDTC_BY_ID_LOADING",

	GET_SHIFTDETAIL_SUCCESS: "GET_SHIFTDETAIL_SUCCESS",
	GET_SHIFTDETAIL_FAILURE: "GET_SHIFTDETAIL_FAILURE",
	GET_SHIFTDETAIL_LOADING: "GET_SHIFTDETAIL_LOADING",
};
