export const permissionsType = {
	GET_PERMISSIONS_LOADING: "GET_PERMISSIONS_LOADING",
	GET_PERMISSIONS_FAILURE: "GET_PERMISSIONS_FAILURE",
	GET_PERMISSIONS_SUCCESS: "GET_PERMISSIONS_SUCCESS",

	GET_SYSTEMUSER_PERMISSIONS_LOADING: "GET_SYSTEMUSER_PERMISSIONS_LOADING",
	GET_SYSTEMUSER_PERMISSIONS_FAILURE: "GET_SYSTEMUSER_PERMISSIONS_FAILURE",
	GET_SYSTEMUSER_PERMISSIONS_SUCCESS: "GET_SYSTEMUSER_PERMISSIONS_SUCCESS",
};
