export const coatingProductionType = {
	GET_COATIONPRODUCTION_FAILURE: "GET_COATIONPRODUCTION_FAILURE",
	GET_COATIONPRODUCTION_SUCCESS: "GET_COATIONPRODUCTION_SUCCESS",
	GET_COATIONPRODUCTION_LOADING: "GET_COATIONPRODUCTION_LOADING",
};
