export const configTypes = {
	GET_ALL_ITEMEDITFIELD_SUCCESS: "GET_ALL_ITEMEDITFIELD_SUCCESS",
	GET_ALL_ITEMEDITFIELD_LOADING: "GET_ALL_ITEMEDITFIELD_LOADING",
	GET_ALL_ITEMEDITFIELD_FAILURE: "GET_ALL_ITEMEDITFIELD_FAILURE",
};
