export const orderTypes = {
	GET_ALL_ORDER_LOADING: "GET_ALL_ORDER_LOADING",
	GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
	GET_ALL_ORDER_FAILURE: "GET_ALL_ORDER_FAILURE",

	FILE_ID: "FILE_ID",
	REMOVE_FILE_ID: "REMOVE_FILE_ID",

	GET_ALL_ACCEPTED_ORDER_SUCCESS: "GET_ALL_ACCEPTED_ORDER_SUCCESS",

	GET_ALL_ORDER_COUNT_LOADING: "GET_ALL_ORDER_COUNT_LOADING",
	GET_ALL_ORDER_COUNT_SUCCESS: "GET_ALL_ORDER_COUNT_SUCCESS",
	GET_ALL_ORDER_COUNT_FAILURE: "GET_ALL_ORDER_COUNT_FAILURE",

	GET_ALL_PENDING_ORDER_COUNT_LOADING: "GET_ALL_PENDING_ORDER_COUNT_LOADING",
	GET_ALL_PENDING_ORDER_COUNT_SUCCESS: "GET_ALL_PENDING_ORDER_COUNT_SUCCESS",
	GET_ALL_PENDING_ORDER_COUNT_FAILURE: "GET_ALL_PENDING_ORDER_COUNT_FAILURE",

	GET_ALL_RECHECK_ORDER_COUNT_LOADING: "GET_ALL_RECHECK_ORDER_COUNT_LOADING",
	GET_ALL_RECHECK_ORDER_COUNT_SUCCESS: "GET_ALL_RECHECK_ORDER_COUNT_SUCCESS",
	GET_ALL_RECHECK_ORDER_COUNT_FAILURE: "GET_ALL_RECHECK_ORDER_COUNT_FAILURE",

	GET_ALL_ORDERITEM_SUCCESS: "GET_ALL_ORDERITEM_SUCCESS",
	GET_ALL_ORDERITEM_LOADING: "GET_ALL_ORDERITEM_LOADING",
	GET_ALL_ORDERITEM_FAILURE: "GET_ALL_ORDERITEM_FAILURE",

	CURRENT_VIEW_ORDERID: "CURRENT_VIEW_ORDERID",
	SET_DRAWER_SALES_QUERY: "SET_DRAWER_SALES_QUERY",

	GETCOUNT: "GETCOUNT",
	GET_ALL_WORKORDER_SUCCESS: "GET_ALL_WORKORDER_SUCCESS",
	GET_ALL_WORKORDER__LOADING: "GET_ALL_WORKORDER__LOADING",
	GET_ALL_WORKORDER__FAILURE: "GET_ALL_WORKORDER__FAILURE",

	GET_ALL_TOTALSHIFTCOUNT_SUCCESS: "GET_ALL_TOTALSHIFTCOUNT_SUCCESS",
	GET_ALL_TOTALSHIFTCOUNT_LOADING: "GET_ALL_TOTALSHIFTCOUNT_LOADING",
	GET_ALL_TOTALSHIFTCOUNT_FAILURE: "GET_ALL_TOTALSHIFTCOUNT_FAILURE",

	INDIVIDUAL_ITEM: "INDIVIDUAL_ITEM",
	INDIVIDUAL_ITEM_DETAILS: "INDIVIDUAL_ITEM_DETAILS",

	GET_ALL_PACKINGITEMS_SUCCESS: "GET_ALL_PACKINGITEMS_SUCCESS",
	GET_ALL_PACKINGITEMS_LOADING: "GET_ALL_PACKINGITEMS_LOADING",
	GET_ALL_PACKINGITEMS_FAILURE: "GET_ALL_PACKINGITEMS_FAILURE",

	GET_ALL_DISPATCHITEMS_SUCCESS: "GET_ALL_DISPATCHITEMS_SUCCESS",
	GET_ALL_DISPATCHITEMS_LOADING: "GET_ALL_DISPATCHITEMS_LOADING",
	GET_ALL_DISPATCHITEMS_FAILURE: "GET_ALL_DISPATCHITEMS_FAILURE",

	GET_SALES_EXCEL_UPLOAD_LOADING: "GET_SALES_EXCEL_UPLOAD_LOADING",
	GET_SALES_EXCEL_UPLOAD_SUCCESS: "GET_SALES_EXCEL_UPLOAD_SUCCESS",
	GET_SALES_EXCEL_UPLOAD_FAILURE: "GET_SALES_EXCEL_UPLOAD_FAILURE",
};
