export const userTypes = {
	GET_USER_LOADING: "GET_USER_LOADING",
	GET_USER_SUCCESS: "GET_USER_SUCCESS",
	GET_USER_FAILURE: "GET_USER_FAILURE",

	GET_USERS_LOADING: "GET_USERS_LOADING",
	GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
	GET_USERS_FAILURE: "GET_USERS_FAILURE",

	GET_ROLES_LOADING: "GET_ROLES_LOADING",
	GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
	GET_ROLES_FAILURE: "GET_ROLES_FAILURE",

	GET_USER_CONFIG_LOADING: "GET_USER_CONFIG_LOADING",
	GET_USER_CONFIG_SUCCESS: "GET_USER_CONFIG_SUCCESS",
	GET_USER_CONFIG_FAILURE: "GET_USER_CONFIG_FAILURE",

	ACTIVE_ROLE: "ACTIVE_ROLE",
	SET_USERS_QUERIES: "SET_USERS_QUERIES",
};
