export const productionReportType = {
	GET_PRODUCTIONREPORT_FAILURE: "GET_PRODUCTIONREPORT_FAILURE",
	GET_PRODUCTIONREPORT_SUCCESS: "GET_PRODUCTIONREPORT_SUCCESS",
	GET_PRODUCTIONREPORT_LOADING: "GET_PRODUCTIONREPORT_LOADING",
};
