export const monitorsheetType = {
	GET_ORDERMONITOR_FAILURE: "GET_ORDERMONITOR_FAILURE",
	GET_ORDERMONITOR_SUCCESS: "GET_ORDERMONITOR_SUCCESS",
	GET_ORDERMONITOR_LOADING: "GET_ORDERMONITOR_LOADING",
};
